-- Database Schema Snapshot
-- Generated: 2025-11-18 06:36:42
-- Database: neondb
-- Generated by: /bigtidy living documentation system

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (aa1f746)
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: update_dataset_modified_date(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_dataset_modified_date() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.last_modified_date = CURRENT_DATE;
  RETURN NEW;
END;
$$;


--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ahe_grain_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ahe_grain_data (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    lab_no character varying(50),
    length_um numeric(10,2),
    half_width_um numeric(10,2),
    rs_um numeric(10,2),
    mass_mg numeric(10,6),
    terminations character varying(10),
    u_ppm numeric(10,3),
    th_ppm numeric(10,3),
    sm_ppm numeric(10,3),
    eu_ppm numeric(10,3),
    he_ncc numeric(12,6),
    uncorr_age_ma numeric(10,2),
    corr_age_ma numeric(10,2),
    corr_age_1sigma_ma numeric(10,2),
    ft numeric(6,4),
    std_run character varying(10),
    thermal_model character varying(10),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ahe_grain_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ahe_grain_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ahe_grain_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ahe_grain_data_id_seq OWNED BY public.ahe_grain_data.id;


--
-- Name: batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batches (
    id integer NOT NULL,
    batch_name character varying(200) NOT NULL,
    analysis_date date,
    laboratory character varying(200),
    analytical_session character varying(200),
    irradiation_id character varying(100),
    irradiation_reactor character varying(100),
    thermal_neutron_dose numeric(18,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.batches_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: batches_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.batches_id_seq OWNED BY public.batches.id;


--
-- Name: datapoint_people_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.datapoint_people_roles (
    id integer NOT NULL,
    datapoint_id integer NOT NULL,
    datapoint_type character varying(20) NOT NULL,
    person_id integer NOT NULL,
    role character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_datapoint_type CHECK (((datapoint_type)::text = ANY ((ARRAY['ft'::character varying, 'he'::character varying, 'upb'::character varying, 'trace'::character varying])::text[])))
);


--
-- Name: datapoint_people_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.datapoint_people_roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: datapoint_people_roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.datapoint_people_roles_id_seq OWNED BY public.datapoint_people_roles.id;


--
-- Name: datasets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.datasets (
    id integer NOT NULL,
    dataset_name character varying(200) NOT NULL,
    description text,
    publication_reference text,
    doi character varying(100),
    study_area character varying(200),
    analyst character varying(100),
    laboratory character varying(200),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: datasets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.datasets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: datasets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.datasets_id_seq OWNED BY public.datasets.id;


--
-- Name: ft_binned_length_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ft_binned_length_data (
    id integer NOT NULL,
    ft_datapoint_id integer NOT NULL,
    mount_id character varying(50),
    etch_duration_seconds integer,
    bin_0_1_um integer,
    bin_1_2_um integer,
    bin_2_3_um integer,
    bin_3_4_um integer,
    bin_4_5_um integer,
    bin_5_6_um integer,
    bin_6_7_um integer,
    bin_7_8_um integer,
    bin_8_9_um integer,
    bin_9_10_um integer,
    bin_10_11_um integer,
    bin_11_12_um integer,
    bin_12_13_um integer,
    bin_13_14_um integer,
    bin_14_15_um integer,
    bin_15_16_um integer,
    bin_16_17_um integer,
    bin_17_18_um integer,
    bin_18_19_um integer,
    bin_19_20_um integer,
    dpar_um numeric(6,3),
    dpar_error_um numeric(6,3),
    n_dpar_measurements integer,
    dper_um numeric(6,3),
    dper_error_um numeric(6,3),
    n_dper_measurements integer,
    dpar_dper_error_type character varying(20),
    comments text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ft_binned_length_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ft_binned_length_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ft_binned_length_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ft_binned_length_data_id_seq OWNED BY public.ft_binned_length_data.id;


--
-- Name: ft_count_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ft_count_data (
    id integer NOT NULL,
    ft_datapoint_id integer NOT NULL,
    grain_id character varying(100) NOT NULL,
    counting_area_cm2 numeric(10,6),
    ns integer,
    rho_s_cm2 numeric(12,2),
    ni integer,
    rho_i_cm2 numeric(12,2),
    nd integer,
    rho_d_cm2 numeric(12,2),
    dpar_um numeric(6,3),
    dpar_error_um numeric(6,3),
    n_dpar_measurements integer,
    dper_um numeric(6,3),
    dper_error_um numeric(6,3),
    n_dper_measurements integer,
    dpar_dper_error_type character varying(20),
    comments text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ft_count_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ft_count_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ft_count_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ft_count_data_id_seq OWNED BY public.ft_count_data.id;


--
-- Name: ft_datapoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ft_datapoints (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    datapoint_key character varying(100) NOT NULL,
    batch_id integer,
    laboratory character varying(200),
    analyst_orcid character varying(50),
    analysis_date timestamp without time zone,
    publication_doi character varying(100),
    mineral_type character varying(50),
    ft_method character varying(50),
    ft_software character varying(100),
    ft_algorithm character varying(50),
    u_determination_method character varying(100),
    n_grains integer,
    total_area_cm2 numeric(10,6),
    mean_rho_s numeric(12,2),
    total_ns integer,
    mean_rho_i numeric(12,2),
    total_ni integer,
    mean_rho_d numeric(12,2),
    total_nd integer,
    dosimeter character varying(50),
    mean_u_ppm numeric(10,3),
    sd_u_ppm numeric(10,3),
    mean_dpar_um numeric(6,3),
    se_dpar_um numeric(6,3),
    n_dpar_measurements integer,
    mean_dper_um numeric(6,3),
    se_dper_um numeric(6,3),
    n_dper_measurements integer,
    mean_rmr0 numeric(6,4),
    sd_rmr0 numeric(6,4),
    mean_kappa numeric(6,4),
    sd_kappa numeric(6,4),
    rmr0_equation character varying(100),
    chi_square numeric(12,6),
    p_chi2_pct numeric(6,3),
    dispersion_pct numeric(6,4),
    age_equation character varying(100),
    mean_age_ma numeric(10,2),
    mean_age_error_ma numeric(10,2),
    central_age_ma numeric(10,2),
    central_age_error_ma numeric(10,2),
    pooled_age_ma numeric(10,2),
    pooled_age_error_ma numeric(10,2),
    population_age_ma numeric(10,2),
    population_age_error_ma numeric(10,2),
    age_error_type character varying(20),
    age_comment text,
    mean_track_length_um numeric(6,3),
    se_mean_track_length_um numeric(6,3),
    n_track_measurements integer,
    sd_track_length_um numeric(6,3),
    cf252_irradiation boolean,
    etchant_chemical character varying(100),
    etch_duration_seconds integer,
    etch_temperature_c numeric(5,2),
    zeta_yr_cm2 numeric(12,6),
    zeta_error_yr_cm2 numeric(12,6),
    zeta_error_type character varying(20),
    r_um numeric(8,3),
    lambda_d character varying(30),
    lambda_f character varying(30),
    q_factor numeric(6,4),
    irradiation_reactor character varying(100),
    thermal_neutron_dose numeric(18,2),
    irradiation_batch_id character varying(100),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ft_datapoints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ft_datapoints_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ft_datapoints_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ft_datapoints_id_seq OWNED BY public.ft_datapoints.id;


--
-- Name: ft_single_grain_ages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ft_single_grain_ages (
    id integer NOT NULL,
    ft_datapoint_id integer NOT NULL,
    grain_id character varying(100) NOT NULL,
    mount_id character varying(50),
    etch_duration_seconds integer,
    u_ppm numeric(10,3),
    u_ppm_error numeric(10,3),
    u_ca_ratio numeric(10,6),
    u_ca_ratio_error numeric(10,6),
    u_ca_error_type character varying(20),
    rmr0 numeric(6,4),
    kappa numeric(6,4),
    grain_age_ma numeric(10,2),
    grain_age_error_ma numeric(10,2),
    grain_age_error_type character varying(20),
    comments text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ft_single_grain_ages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ft_single_grain_ages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ft_single_grain_ages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ft_single_grain_ages_id_seq OWNED BY public.ft_single_grain_ages.id;


--
-- Name: ft_track_length_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ft_track_length_data (
    id integer NOT NULL,
    ft_datapoint_id integer NOT NULL,
    grain_id character varying(100) NOT NULL,
    track_id character varying(100) NOT NULL,
    track_type character varying(20),
    mount_id character varying(50),
    etch_duration_seconds integer,
    apparent_length_um numeric(6,3),
    corrected_z_depth_um numeric(8,2),
    true_length_um numeric(6,3),
    azimuth_deg numeric(6,2),
    dip_deg numeric(6,2),
    angle_to_c_axis_deg numeric(6,2),
    c_axis_corrected_length_um numeric(6,3),
    dpar_um numeric(6,3),
    dpar_error_um numeric(6,3),
    n_dpar_measurements integer,
    dper_um numeric(6,3),
    dper_error_um numeric(6,3),
    n_dper_measurements integer,
    dpar_dper_error_type character varying(20),
    rmr0 numeric(6,4),
    kappa numeric(6,4),
    comments text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_track_type CHECK (((track_type)::text = ANY ((ARRAY['TINT'::character varying, 'TINCLE'::character varying, 'semi-track'::character varying, NULL::character varying])::text[])))
);


--
-- Name: ft_track_length_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ft_track_length_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ft_track_length_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ft_track_length_data_id_seq OWNED BY public.ft_track_length_data.id;


--
-- Name: grains; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grains (
    id integer NOT NULL,
    grain_id character varying(100) NOT NULL,
    mount_id character varying(50),
    grain_identifier character varying(100),
    grain_morphology character varying(50),
    grain_quality character varying(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: grains_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.grains_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: grains_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.grains_id_seq OWNED BY public.grains.id;


--
-- Name: he_datapoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.he_datapoints (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    datapoint_key character varying(100) NOT NULL,
    batch_id integer,
    laboratory character varying(200),
    analyst_orcid character varying(50),
    analysis_date timestamp without time zone,
    publication_doi character varying(100),
    mineral_type character varying(50),
    mount_id character varying(50),
    n_aliquots integer,
    mean_uncorr_age_ma numeric(10,2),
    mean_uncorr_age_error_ma numeric(10,2),
    mean_uncorr_age_error_type character varying(20),
    weighted_mean_uncorr_age_ma numeric(10,2),
    weighted_mean_uncorr_age_error_ma numeric(10,2),
    weighted_mean_uncorr_age_error_type character varying(20),
    mswd_uncorr numeric(8,4),
    conf95_uncorr_ma numeric(10,2),
    chi2_uncorr_pct numeric(6,3),
    iqr_uncorr_ma numeric(10,2),
    mean_corr_age_ma numeric(10,2),
    mean_corr_age_error_ma numeric(10,2),
    mean_corr_age_error_type character varying(20),
    weighted_mean_corr_age_ma numeric(10,2),
    weighted_mean_corr_age_error_ma numeric(10,2),
    weighted_mean_corr_age_error_type character varying(20),
    mswd_corr numeric(8,4),
    conf95_corr_ma numeric(10,2),
    chi2_corr_pct numeric(6,3),
    iqr_corr_ma numeric(10,2),
    uncertainty_description text,
    ablation_pit_volume_method character varying(100),
    ablation_pit_volume_software character varying(100),
    he_measurement_method character varying(100),
    parent_isotope_method character varying(100),
    surface_area_volume_equation character varying(100),
    alpha_stopping_distance_ref character varying(200),
    ft_correction_equation character varying(100),
    esr_sa_v_equation character varying(100),
    esr_ft_equation character varying(100),
    eu_equation character varying(100),
    he_age_approach character varying(100),
    corr_age_method character varying(100),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: he_datapoints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.he_datapoints_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: he_datapoints_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.he_datapoints_id_seq OWNED BY public.he_datapoints.id;


--
-- Name: he_whole_grain_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.he_whole_grain_data (
    id integer NOT NULL,
    he_datapoint_id integer NOT NULL,
    lab_no character varying(50),
    grain_identifier character varying(100),
    aliquot_type character varying(20),
    n_grains_in_aliquot integer,
    crystal_integrity character varying(20),
    grain_morphology character varying(50),
    assumed_geometry character varying(50),
    length_um numeric(10,2),
    length_um_sd numeric(10,2),
    half_width_um numeric(10,2),
    width_um_sd numeric(10,2),
    height_um numeric(10,2),
    height_um_sd numeric(10,2),
    measurement_method character varying(100),
    crystal_faces_measured character varying(200),
    he_ncc numeric(12,6),
    he_measurement_method character varying(100),
    he_extraction_temperature_c numeric(6,2),
    he_extraction_duration_min integer,
    he_extraction_method character varying(100),
    he_blank_ncc numeric(12,6),
    he_blank_error_ncc numeric(12,6),
    u_ppm numeric(10,3),
    u_ppm_error numeric(10,3),
    th_ppm numeric(10,3),
    th_ppm_error numeric(10,3),
    sm_ppm numeric(10,3),
    sm_ppm_error numeric(10,3),
    eu_ppm numeric(10,3),
    u_measurement_method character varying(100),
    u_blank_ppm numeric(10,6),
    th_blank_ppm numeric(10,6),
    sm_blank_ppm numeric(10,6),
    spike_u238_u235_ratio numeric(10,6),
    spike_th232_th229_ratio numeric(10,6),
    mass_mg numeric(10,6),
    surface_area_mm2 numeric(10,6),
    volume_mm3 numeric(10,6),
    sa_v_ratio numeric(10,6),
    rs_um numeric(10,2),
    esr_sa_v_um numeric(10,2),
    esr_ft_um numeric(10,2),
    sa_v_calc_equation character varying(100),
    ft_correction_equation character varying(100),
    alpha_stopping_distance_ref character varying(200),
    uncorr_age_ma numeric(10,2),
    uncorr_age_error_ma numeric(10,2),
    corr_age_ma numeric(10,2),
    corr_age_error_ma numeric(10,2),
    corr_age_1sigma_ma numeric(10,2),
    ft numeric(6,4),
    error_type character varying(20),
    eu_equation character varying(100),
    he_age_approach character varying(100),
    lambda_u238 character varying(30),
    lambda_th232 character varying(30),
    lambda_sm147 character varying(30),
    terminations character varying(10),
    std_run character varying(10),
    thermal_model character varying(10),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: he_whole_grain_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.he_whole_grain_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: he_whole_grain_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.he_whole_grain_data_id_seq OWNED BY public.he_whole_grain_data.id;


--
-- Name: mounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mounts (
    id integer NOT NULL,
    mount_id character varying(50) NOT NULL,
    mount_name character varying(200),
    mount_date date,
    sample_id character varying(50),
    etchant_chemical character varying(100),
    etch_duration_seconds integer,
    etch_temperature_c numeric(5,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: mounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.mounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: mounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.mounts_id_seq OWNED BY public.mounts.id;


--
-- Name: people; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people (
    id integer NOT NULL,
    orcid character varying(50),
    name character varying(200) NOT NULL,
    email character varying(200),
    affiliation character varying(300),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_orcid_or_name CHECK (((orcid IS NOT NULL) OR (name IS NOT NULL)))
);


--
-- Name: people_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.people_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: people_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.people_id_seq OWNED BY public.people.id;


--
-- Name: reference_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reference_materials (
    id integer NOT NULL,
    batch_id integer NOT NULL,
    material_name character varying(100) NOT NULL,
    material_type character varying(50),
    expected_age_ma numeric(10,2),
    expected_age_error_ma numeric(10,2),
    measured_age_ma numeric(10,2),
    measured_age_error_ma numeric(10,2),
    parameter_type character varying(50),
    measured_value numeric(15,6),
    expected_value numeric(15,6),
    error numeric(15,6),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: reference_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reference_materials_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: reference_materials_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reference_materials_id_seq OWNED BY public.reference_materials.id;


--
-- Name: sample_people_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_people_roles (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    person_id integer NOT NULL,
    role character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: sample_people_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_people_roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_people_roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_people_roles_id_seq OWNED BY public.sample_people_roles.id;


--
-- Name: samples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.samples (
    sample_id character varying(50) NOT NULL,
    dataset_id integer DEFAULT 1,
    igsn character varying(20),
    latitude numeric(10,7),
    longitude numeric(10,7),
    elevation_m numeric(8,2),
    geodetic_datum character varying(20) DEFAULT 'WGS84'::character varying,
    vertical_datum character varying(50) DEFAULT 'mean sea level'::character varying,
    lat_long_precision_m integer,
    lithology character varying(100),
    mineral_type character varying(50),
    sample_kind character varying(100),
    sample_method character varying(100),
    sample_depth_m numeric(8,2),
    sampling_location_information text,
    stratigraphic_unit character varying(200),
    chronostratigraphic_unit_age character varying(100),
    sample_age_ma numeric(10,2),
    sample_collector character varying(200),
    collection_date date,
    analyst character varying(100),
    analysis_method character varying(100),
    last_known_sample_archive character varying(200),
    associated_references text,
    n_aft_grains integer,
    n_ahe_grains integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ahe_grain_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ahe_grain_data ALTER COLUMN id SET DEFAULT nextval('public.ahe_grain_data_id_seq'::regclass);


--
-- Name: batches id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batches ALTER COLUMN id SET DEFAULT nextval('public.batches_id_seq'::regclass);


--
-- Name: datapoint_people_roles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datapoint_people_roles ALTER COLUMN id SET DEFAULT nextval('public.datapoint_people_roles_id_seq'::regclass);


--
-- Name: datasets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets ALTER COLUMN id SET DEFAULT nextval('public.datasets_id_seq'::regclass);


--
-- Name: ft_binned_length_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_binned_length_data ALTER COLUMN id SET DEFAULT nextval('public.ft_binned_length_data_id_seq'::regclass);


--
-- Name: ft_count_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_count_data ALTER COLUMN id SET DEFAULT nextval('public.ft_count_data_id_seq'::regclass);


--
-- Name: ft_datapoints id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_datapoints ALTER COLUMN id SET DEFAULT nextval('public.ft_datapoints_id_seq'::regclass);


--
-- Name: ft_single_grain_ages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_single_grain_ages ALTER COLUMN id SET DEFAULT nextval('public.ft_single_grain_ages_id_seq'::regclass);


--
-- Name: ft_track_length_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_track_length_data ALTER COLUMN id SET DEFAULT nextval('public.ft_track_length_data_id_seq'::regclass);


--
-- Name: grains id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grains ALTER COLUMN id SET DEFAULT nextval('public.grains_id_seq'::regclass);


--
-- Name: he_datapoints id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_datapoints ALTER COLUMN id SET DEFAULT nextval('public.he_datapoints_id_seq'::regclass);


--
-- Name: he_whole_grain_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_whole_grain_data ALTER COLUMN id SET DEFAULT nextval('public.he_whole_grain_data_id_seq'::regclass);


--
-- Name: mounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mounts ALTER COLUMN id SET DEFAULT nextval('public.mounts_id_seq'::regclass);


--
-- Name: people id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people ALTER COLUMN id SET DEFAULT nextval('public.people_id_seq'::regclass);


--
-- Name: reference_materials id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_materials ALTER COLUMN id SET DEFAULT nextval('public.reference_materials_id_seq'::regclass);


--
-- Name: sample_people_roles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_people_roles ALTER COLUMN id SET DEFAULT nextval('public.sample_people_roles_id_seq'::regclass);


--
-- Name: ahe_grain_data ahe_grain_data_lab_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ahe_grain_data
    ADD CONSTRAINT ahe_grain_data_lab_no_key UNIQUE (lab_no);


--
-- Name: ahe_grain_data ahe_grain_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ahe_grain_data
    ADD CONSTRAINT ahe_grain_data_pkey PRIMARY KEY (id);


--
-- Name: batches batches_batch_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batches
    ADD CONSTRAINT batches_batch_name_key UNIQUE (batch_name);


--
-- Name: batches batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batches
    ADD CONSTRAINT batches_pkey PRIMARY KEY (id);


--
-- Name: datapoint_people_roles datapoint_people_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datapoint_people_roles
    ADD CONSTRAINT datapoint_people_roles_pkey PRIMARY KEY (id);


--
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (id);


--
-- Name: ft_binned_length_data ft_binned_length_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_binned_length_data
    ADD CONSTRAINT ft_binned_length_data_pkey PRIMARY KEY (id);


--
-- Name: ft_count_data ft_count_data_ft_datapoint_id_grain_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_count_data
    ADD CONSTRAINT ft_count_data_ft_datapoint_id_grain_id_key UNIQUE (ft_datapoint_id, grain_id);


--
-- Name: ft_count_data ft_count_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_count_data
    ADD CONSTRAINT ft_count_data_pkey PRIMARY KEY (id);


--
-- Name: ft_datapoints ft_datapoints_datapoint_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_datapoints
    ADD CONSTRAINT ft_datapoints_datapoint_key_key UNIQUE (datapoint_key);


--
-- Name: ft_datapoints ft_datapoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_datapoints
    ADD CONSTRAINT ft_datapoints_pkey PRIMARY KEY (id);


--
-- Name: ft_single_grain_ages ft_single_grain_ages_ft_datapoint_id_grain_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_single_grain_ages
    ADD CONSTRAINT ft_single_grain_ages_ft_datapoint_id_grain_id_key UNIQUE (ft_datapoint_id, grain_id);


--
-- Name: ft_single_grain_ages ft_single_grain_ages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_single_grain_ages
    ADD CONSTRAINT ft_single_grain_ages_pkey PRIMARY KEY (id);


--
-- Name: ft_track_length_data ft_track_length_data_ft_datapoint_id_grain_id_track_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_track_length_data
    ADD CONSTRAINT ft_track_length_data_ft_datapoint_id_grain_id_track_id_key UNIQUE (ft_datapoint_id, grain_id, track_id);


--
-- Name: ft_track_length_data ft_track_length_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_track_length_data
    ADD CONSTRAINT ft_track_length_data_pkey PRIMARY KEY (id);


--
-- Name: grains grains_grain_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grains
    ADD CONSTRAINT grains_grain_id_key UNIQUE (grain_id);


--
-- Name: grains grains_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grains
    ADD CONSTRAINT grains_pkey PRIMARY KEY (id);


--
-- Name: he_datapoints he_datapoints_datapoint_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_datapoints
    ADD CONSTRAINT he_datapoints_datapoint_key_key UNIQUE (datapoint_key);


--
-- Name: he_datapoints he_datapoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_datapoints
    ADD CONSTRAINT he_datapoints_pkey PRIMARY KEY (id);


--
-- Name: he_whole_grain_data he_whole_grain_data_lab_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_whole_grain_data
    ADD CONSTRAINT he_whole_grain_data_lab_no_key UNIQUE (lab_no);


--
-- Name: he_whole_grain_data he_whole_grain_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_whole_grain_data
    ADD CONSTRAINT he_whole_grain_data_pkey PRIMARY KEY (id);


--
-- Name: mounts mounts_mount_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mounts
    ADD CONSTRAINT mounts_mount_id_key UNIQUE (mount_id);


--
-- Name: mounts mounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mounts
    ADD CONSTRAINT mounts_pkey PRIMARY KEY (id);


--
-- Name: people people_orcid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_orcid_key UNIQUE (orcid);


--
-- Name: people people_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_pkey PRIMARY KEY (id);


--
-- Name: reference_materials reference_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_materials
    ADD CONSTRAINT reference_materials_pkey PRIMARY KEY (id);


--
-- Name: sample_people_roles sample_people_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_people_roles
    ADD CONSTRAINT sample_people_roles_pkey PRIMARY KEY (id);


--
-- Name: sample_people_roles sample_people_roles_sample_id_person_id_role_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_people_roles
    ADD CONSTRAINT sample_people_roles_sample_id_person_id_role_key UNIQUE (sample_id, person_id, role);


--
-- Name: samples samples_igsn_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_igsn_key UNIQUE (igsn);


--
-- Name: samples samples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_pkey PRIMARY KEY (sample_id);


--
-- Name: idx_ahe_age; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ahe_age ON public.ahe_grain_data USING btree (corr_age_ma);


--
-- Name: idx_ahe_lab_no; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ahe_lab_no ON public.ahe_grain_data USING btree (lab_no);


--
-- Name: idx_ahe_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ahe_sample ON public.ahe_grain_data USING btree (sample_id);


--
-- Name: idx_batches_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batches_date ON public.batches USING btree (analysis_date);


--
-- Name: idx_batches_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batches_name ON public.batches USING btree (batch_name);


--
-- Name: idx_datapoint_people_datapoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_datapoint_people_datapoint ON public.datapoint_people_roles USING btree (datapoint_id, datapoint_type);


--
-- Name: idx_datapoint_people_person; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_datapoint_people_person ON public.datapoint_people_roles USING btree (person_id);


--
-- Name: idx_ft_binned_length_datapoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_binned_length_datapoint ON public.ft_binned_length_data USING btree (ft_datapoint_id);


--
-- Name: idx_ft_count_data_datapoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_count_data_datapoint ON public.ft_count_data USING btree (ft_datapoint_id);


--
-- Name: idx_ft_count_data_grain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_count_data_grain ON public.ft_count_data USING btree (grain_id);


--
-- Name: idx_ft_datapoints_batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_datapoints_batch ON public.ft_datapoints USING btree (batch_id);


--
-- Name: idx_ft_datapoints_central_age; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_datapoints_central_age ON public.ft_datapoints USING btree (central_age_ma);


--
-- Name: idx_ft_datapoints_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_datapoints_key ON public.ft_datapoints USING btree (datapoint_key);


--
-- Name: idx_ft_datapoints_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_datapoints_sample ON public.ft_datapoints USING btree (sample_id);


--
-- Name: idx_ft_single_grain_datapoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_single_grain_datapoint ON public.ft_single_grain_ages USING btree (ft_datapoint_id);


--
-- Name: idx_ft_single_grain_grain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_single_grain_grain ON public.ft_single_grain_ages USING btree (grain_id);


--
-- Name: idx_ft_track_length_datapoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_track_length_datapoint ON public.ft_track_length_data USING btree (ft_datapoint_id);


--
-- Name: idx_ft_track_length_grain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_track_length_grain ON public.ft_track_length_data USING btree (grain_id);


--
-- Name: idx_ft_track_length_mtl; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ft_track_length_mtl ON public.ft_track_length_data USING btree (true_length_um);


--
-- Name: idx_grains_grain_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_grains_grain_id ON public.grains USING btree (grain_id);


--
-- Name: idx_grains_mount; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_grains_mount ON public.grains USING btree (mount_id);


--
-- Name: idx_he_datapoints_batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_he_datapoints_batch ON public.he_datapoints USING btree (batch_id);


--
-- Name: idx_he_datapoints_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_he_datapoints_key ON public.he_datapoints USING btree (datapoint_key);


--
-- Name: idx_he_datapoints_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_he_datapoints_sample ON public.he_datapoints USING btree (sample_id);


--
-- Name: idx_he_whole_grain_age; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_he_whole_grain_age ON public.he_whole_grain_data USING btree (corr_age_ma);


--
-- Name: idx_he_whole_grain_datapoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_he_whole_grain_datapoint ON public.he_whole_grain_data USING btree (he_datapoint_id);


--
-- Name: idx_he_whole_grain_lab_no; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_he_whole_grain_lab_no ON public.he_whole_grain_data USING btree (lab_no);


--
-- Name: idx_mounts_mount_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mounts_mount_id ON public.mounts USING btree (mount_id);


--
-- Name: idx_mounts_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mounts_sample ON public.mounts USING btree (sample_id);


--
-- Name: idx_people_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_people_name ON public.people USING btree (name);


--
-- Name: idx_people_orcid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_people_orcid ON public.people USING btree (orcid) WHERE (orcid IS NOT NULL);


--
-- Name: idx_ref_materials_batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_materials_batch ON public.reference_materials USING btree (batch_id);


--
-- Name: idx_ref_materials_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_materials_name ON public.reference_materials USING btree (material_name);


--
-- Name: idx_sample_people_person; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_people_person ON public.sample_people_roles USING btree (person_id);


--
-- Name: idx_sample_people_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_people_sample ON public.sample_people_roles USING btree (sample_id);


--
-- Name: idx_samples_dataset; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_dataset ON public.samples USING btree (dataset_id);


--
-- Name: idx_samples_igsn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_igsn ON public.samples USING btree (igsn) WHERE (igsn IS NOT NULL);


--
-- Name: idx_samples_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_location ON public.samples USING btree (latitude, longitude);


--
-- Name: idx_samples_mineral; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_mineral ON public.samples USING btree (mineral_type);


--
-- Name: samples update_samples_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_samples_updated_at BEFORE UPDATE ON public.samples FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ahe_grain_data ahe_grain_data_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ahe_grain_data
    ADD CONSTRAINT ahe_grain_data_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(sample_id) ON DELETE CASCADE;


--
-- Name: datapoint_people_roles datapoint_people_roles_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datapoint_people_roles
    ADD CONSTRAINT datapoint_people_roles_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id) ON DELETE CASCADE;


--
-- Name: ft_binned_length_data ft_binned_length_data_ft_datapoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_binned_length_data
    ADD CONSTRAINT ft_binned_length_data_ft_datapoint_id_fkey FOREIGN KEY (ft_datapoint_id) REFERENCES public.ft_datapoints(id) ON DELETE CASCADE;


--
-- Name: ft_count_data ft_count_data_ft_datapoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_count_data
    ADD CONSTRAINT ft_count_data_ft_datapoint_id_fkey FOREIGN KEY (ft_datapoint_id) REFERENCES public.ft_datapoints(id) ON DELETE CASCADE;


--
-- Name: ft_datapoints ft_datapoints_batch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_datapoints
    ADD CONSTRAINT ft_datapoints_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: ft_single_grain_ages ft_single_grain_ages_ft_datapoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_single_grain_ages
    ADD CONSTRAINT ft_single_grain_ages_ft_datapoint_id_fkey FOREIGN KEY (ft_datapoint_id) REFERENCES public.ft_datapoints(id) ON DELETE CASCADE;


--
-- Name: ft_track_length_data ft_track_length_data_ft_datapoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ft_track_length_data
    ADD CONSTRAINT ft_track_length_data_ft_datapoint_id_fkey FOREIGN KEY (ft_datapoint_id) REFERENCES public.ft_datapoints(id) ON DELETE CASCADE;


--
-- Name: grains grains_mount_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grains
    ADD CONSTRAINT grains_mount_id_fkey FOREIGN KEY (mount_id) REFERENCES public.mounts(mount_id) ON DELETE SET NULL;


--
-- Name: he_datapoints he_datapoints_batch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_datapoints
    ADD CONSTRAINT he_datapoints_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: he_whole_grain_data he_whole_grain_data_he_datapoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.he_whole_grain_data
    ADD CONSTRAINT he_whole_grain_data_he_datapoint_id_fkey FOREIGN KEY (he_datapoint_id) REFERENCES public.he_datapoints(id) ON DELETE CASCADE;


--
-- Name: reference_materials reference_materials_batch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_materials
    ADD CONSTRAINT reference_materials_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batches(id) ON DELETE CASCADE;


--
-- Name: sample_people_roles sample_people_roles_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_people_roles
    ADD CONSTRAINT sample_people_roles_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id) ON DELETE CASCADE;


--
-- Name: samples samples_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id);


--
-- PostgreSQL database dump complete
--

