CREATE TABLE public.ahe_grain_data (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    lab_no character varying(50),
    length_um numeric(10,2),
    half_width_um numeric(10,2),
    rs_um numeric(10,2),
    mass_mg numeric(10,6),
    terminations character varying(10),
    u_ppm numeric(10,3),
    th_ppm numeric(10,3),
    sm_ppm numeric(10,3),
    eu_ppm numeric(10,3),
    he_ncc numeric(12,6),
    uncorr_age_ma numeric(10,2),
    corr_age_ma numeric(10,2),
    ft numeric(6,4),
    std_run character varying(10),
    thermal_model character varying(10),
);
CREATE TABLE public.data_files (
    id integer NOT NULL,
    dataset_id integer NOT NULL,
    file_name character varying(200) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_type character varying(50) NOT NULL,
    display_name character varying(200),
    file_size_bytes integer,
    row_count integer,
    description text,
);
CREATE TABLE public.datasets (
    id integer NOT NULL,
    dataset_name character varying(200) NOT NULL,
    description text,
    publication_reference text,
    doi character varying(100),
    study_area character varying(200),
    analyst character varying(100),
    laboratory character varying(200),
    title character varying(500),
    authors text,
    journal character varying(200),
    year integer,
    methods text,
    num_samples integer,
    age_range_min_ma numeric(10,2),
    age_range_max_ma numeric(10,2),
    collection_date date,
    analysis_methods text[]
);
CREATE TABLE public.ft_ages (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    age_equation character varying(100),
    ft_age_type character varying(50),
    lambda_d character varying(20),
    lambda_f character varying(20),
    dosimeter character varying(50),
    rs_um numeric(8,3),
    q numeric(6,4),
    irradiation_reactor character varying(100),
    n_grains integer,
    pooled_age_ma numeric(10,2),
    pooled_age_error_ma numeric(10,2),
    central_age_ma numeric(10,2),
    central_age_error_ma numeric(10,2),
    dispersion_pct numeric(6,3),
    age_peak_software character varying(100),
    best_fit_peak_ages_ma numeric(10,2)[],
    best_fit_peak_errors_ma numeric(10,2)[],
    best_fit_peak_grain_pct numeric(6,2)[],
);
CREATE TABLE public.ft_counts (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    grain_id character varying(100) NOT NULL,
    ns integer,
    u_ppm numeric(10,3),
    th_ppm numeric(10,3),
    eu_ppm numeric(10,3),
    dpar_um numeric(6,3),
    dpar_sd_um numeric(6,3),
    dper_um numeric(6,3),
    dper_sd_um numeric(6,3),
    cl_wt_pct numeric(6,4),
    ecl_apfu numeric(8,4),
    disp_pct numeric(6,3),
    n_grains integer,
    ft_counting_method character varying(50),
    ft_software character varying(100),
    ft_algorithm character varying(50),
    microscope character varying(100),
    objective character varying(50),
    analyst character varying(100),
    laboratory character varying(100),
    analysis_date date,
    sample_mount_id character varying(50),
    etching_conditions character varying(200),
    ni integer,
    nd integer,
    dosimeter character varying(50),
);
CREATE TABLE public.ft_track_lengths (
    id integer NOT NULL,
    sample_id character varying(50) NOT NULL,
    grain_id character varying(100) NOT NULL,
    n_confined_tracks integer,
    mean_track_length_um numeric(6,3),
    mean_track_length_se_um numeric(6,3),
    mean_track_length_sd_um numeric(6,3),
    dpar_um numeric(6,3),
    dpar_sd_um numeric(6,3),
    dper_um numeric(6,3),
    dper_sd_um numeric(6,3),
    apparent_length_um numeric(6,3),
    true_length_um numeric(6,3),
    angle_to_c_axis_deg numeric(6,2),
    azimuth_deg numeric(6,2),
    dip_deg numeric(6,2),
    corrected_z_depth_um numeric(8,2),
    ft_length_method character varying(50),
    ft_software character varying(100),
    ft_track_type character varying(20),
    microscope character varying(100),
    objective character varying(50),
    analyst character varying(100),
    laboratory character varying(100),
    analysis_date date,
    sample_mount_id character varying(50),
    etching_conditions character varying(200),
);
CREATE TABLE public.samples (
    sample_id character varying(50) NOT NULL,
    igsn character varying(20),
    latitude numeric(10,7),
    longitude numeric(10,7),
    elevation_m numeric(8,2),
    lat_long_precision_m integer,
    lithology character varying(100),
    mineral_type character varying(50),
    sample_kind character varying(100),
    sample_method character varying(100),
    sample_depth_m numeric(8,2),
    sampling_location_information text,
    stratigraphic_unit character varying(200),
    chronostratigraphic_unit_age character varying(100),
    sample_age_ma numeric(10,2),
    sample_collector character varying(200),
    collection_date date,
    analyst character varying(100),
    analysis_method character varying(100),
    last_known_sample_archive character varying(200),
    associated_references text,
    n_aft_grains integer,
    n_ahe_grains integer,
);
CREATE VIEW public.vw_aft_complete AS
CREATE VIEW public.vw_sample_summary AS
