[dotenv@17.2.3] injecting env (6) from .env.local -- tip: 🔐 encrypt with Dotenvx: https://dotenvx.com
-- Database Schema Snapshot
-- Generated: 2025-11-18 01:24:40
-- Database: AusGeochem Thermochronology (Neon PostgreSQL)
-- Generated by: /bigtidy living documentation system

CREATE TABLE ahe_grain_data (
  id integer(32,0) NOT NULL PRIMARY KEY,
  sample_id character varying(50) NOT NULL,
  lab_no character varying(50),
  length_um numeric(10,2),
  half_width_um numeric(10,2),
  rs_um numeric(10,2),
  mass_mg numeric(10,6),
  terminations character varying(10),
  u_ppm numeric(10,3),
  th_ppm numeric(10,3),
  sm_ppm numeric(10,3),
  eu_ppm numeric(10,3),
  he_ncc numeric(12,6),
  uncorr_age_ma numeric(10,2),
  corr_age_ma numeric(10,2),
  corr_age_1sigma_ma numeric(10,2),
  ft numeric(6,4),
  std_run character varying(10),
  thermal_model character varying(10),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: ahe_grain_data.sample_id -> samples.sample_id

CREATE TABLE batches (
  id integer(32,0) NOT NULL PRIMARY KEY,
  batch_name character varying(200) NOT NULL,
  analysis_date date,
  laboratory character varying(200),
  analytical_session character varying(200),
  irradiation_id character varying(100),
  irradiation_reactor character varying(100),
  thermal_neutron_dose numeric(18,2),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE data_files (
  id integer(32,0) NOT NULL PRIMARY KEY,
  dataset_id integer(32,0) NOT NULL,
  file_name character varying(200) NOT NULL,
  file_path character varying(500) NOT NULL,
  file_type character varying(50) NOT NULL,
  display_name character varying(200),
  file_size_bytes integer(32,0),
  row_count integer(32,0),
  description text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_folder boolean DEFAULT false,
  folder_path character varying(500)
);

-- FK: data_files.dataset_id -> datasets.id

CREATE TABLE datapoint_people_roles (
  id integer(32,0) NOT NULL PRIMARY KEY,
  datapoint_id integer(32,0) NOT NULL,
  datapoint_type character varying(20) NOT NULL,
  person_id integer(32,0) NOT NULL,
  role character varying(50) NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: datapoint_people_roles.person_id -> people.id

CREATE TABLE datasets (
  id integer(32,0) NOT NULL PRIMARY KEY,
  dataset_name character varying(200) NOT NULL,
  description text,
  publication_reference text,
  doi character varying(100),
  study_area character varying(200),
  analyst character varying(100),
  laboratory character varying(200),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  full_citation text,
  publication_year integer(32,0),
  publication_journal character varying(200),
  publication_volume_pages character varying(100),
  study_location text,
  pdf_filename character varying(500),
  pdf_url text,
  mineral_analyzed character varying(100),
  sample_count integer(32,0),
  age_range_min_ma numeric(10,2),
  age_range_max_ma numeric(10,2),
  authors ARRAY,
  collection_date date,
  analysis_methods ARRAY
);

CREATE TABLE fair_score_breakdown (
  id integer(32,0) NOT NULL PRIMARY KEY,
  dataset_id integer(32,0) NOT NULL,
  table4_score integer(32,0),
  table4_reasoning text,
  table5_score integer(32,0),
  table5_reasoning text,
  table6_score integer(32,0),
  table6_reasoning text,
  table10_score integer(32,0),
  table10_reasoning text,
  findable_score integer(32,0),
  findable_reasoning text,
  accessible_score integer(32,0),
  accessible_reasoning text,
  interoperable_score integer(32,0),
  interoperable_reasoning text,
  reusable_score integer(32,0),
  reusable_reasoning text,
  total_score integer(32,0),
  grade character varying(2),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: fair_score_breakdown.dataset_id -> datasets.id

CREATE TABLE ft_binned_length_data (
  id integer(32,0) NOT NULL PRIMARY KEY,
  ft_datapoint_id integer(32,0) NOT NULL,
  mount_id character varying(50),
  etch_duration_seconds integer(32,0),
  bin_0_1_um integer(32,0),
  bin_1_2_um integer(32,0),
  bin_2_3_um integer(32,0),
  bin_3_4_um integer(32,0),
  bin_4_5_um integer(32,0),
  bin_5_6_um integer(32,0),
  bin_6_7_um integer(32,0),
  bin_7_8_um integer(32,0),
  bin_8_9_um integer(32,0),
  bin_9_10_um integer(32,0),
  bin_10_11_um integer(32,0),
  bin_11_12_um integer(32,0),
  bin_12_13_um integer(32,0),
  bin_13_14_um integer(32,0),
  bin_14_15_um integer(32,0),
  bin_15_16_um integer(32,0),
  bin_16_17_um integer(32,0),
  bin_17_18_um integer(32,0),
  bin_18_19_um integer(32,0),
  bin_19_20_um integer(32,0),
  dpar_um numeric(6,3),
  dpar_error_um numeric(6,3),
  n_dpar_measurements integer(32,0),
  dper_um numeric(6,3),
  dper_error_um numeric(6,3),
  n_dper_measurements integer(32,0),
  dpar_dper_error_type character varying(20),
  comments text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: ft_binned_length_data.ft_datapoint_id -> ft_datapoints.id

CREATE TABLE ft_count_data (
  id integer(32,0) NOT NULL PRIMARY KEY,
  ft_datapoint_id integer(32,0) NOT NULL,
  grain_id character varying(100) NOT NULL,
  counting_area_cm2 numeric(10,6),
  ns integer(32,0),
  rho_s_cm2 numeric(12,2),
  ni integer(32,0),
  rho_i_cm2 numeric(12,2),
  nd integer(32,0),
  rho_d_cm2 numeric(12,2),
  dpar_um numeric(6,3),
  dpar_error_um numeric(6,3),
  n_dpar_measurements integer(32,0),
  dper_um numeric(6,3),
  dper_error_um numeric(6,3),
  n_dper_measurements integer(32,0),
  dpar_dper_error_type character varying(20),
  comments text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: ft_count_data.ft_datapoint_id -> ft_datapoints.id

CREATE TABLE ft_datapoints (
  id integer(32,0) NOT NULL PRIMARY KEY,
  sample_id character varying(50) NOT NULL,
  datapoint_key character varying(100) NOT NULL,
  batch_id integer(32,0),
  laboratory character varying(200),
  analyst_orcid character varying(50),
  analysis_date timestamp without time zone,
  publication_doi character varying(100),
  mineral_type character varying(50),
  ft_method character varying(50),
  ft_software character varying(100),
  ft_algorithm character varying(50),
  u_determination_method character varying(100),
  n_grains integer(32,0),
  total_area_cm2 numeric(10,6),
  mean_rho_s numeric(12,2),
  total_ns integer(32,0),
  mean_rho_i numeric(12,2),
  total_ni integer(32,0),
  mean_rho_d numeric(12,2),
  total_nd integer(32,0),
  dosimeter character varying(50),
  mean_u_ppm numeric(10,3),
  sd_u_ppm numeric(10,3),
  mean_dpar_um numeric(6,3),
  se_dpar_um numeric(6,3),
  n_dpar_measurements integer(32,0),
  mean_dper_um numeric(6,3),
  se_dper_um numeric(6,3),
  n_dper_measurements integer(32,0),
  mean_rmr0 numeric(6,4),
  sd_rmr0 numeric(6,4),
  mean_kappa numeric(6,4),
  sd_kappa numeric(6,4),
  rmr0_equation character varying(100),
  chi_square numeric(12,6),
  p_chi2_pct numeric(6,3),
  dispersion_pct numeric(6,4),
  age_equation character varying(100),
  mean_age_ma numeric(10,2),
  mean_age_error_ma numeric(10,2),
  central_age_ma numeric(10,2),
  central_age_error_ma numeric(10,2),
  pooled_age_ma numeric(10,2),
  pooled_age_error_ma numeric(10,2),
  population_age_ma numeric(10,2),
  population_age_error_ma numeric(10,2),
  age_error_type character varying(20),
  age_comment text,
  mean_track_length_um numeric(6,3),
  se_mean_track_length_um numeric(6,3),
  n_track_measurements integer(32,0),
  sd_track_length_um numeric(6,3),
  cf252_irradiation boolean,
  etchant_chemical character varying(100),
  etch_duration_seconds integer(32,0),
  etch_temperature_c numeric(5,2),
  zeta_yr_cm2 numeric(12,6),
  zeta_error_yr_cm2 numeric(12,6),
  zeta_error_type character varying(20),
  r_um numeric(8,3),
  lambda_d character varying(30),
  lambda_f character varying(30),
  q_factor numeric(6,4),
  irradiation_reactor character varying(100),
  thermal_neutron_dose numeric(18,2),
  irradiation_batch_id character varying(100),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: ft_datapoints.batch_id -> batches.id

CREATE TABLE ft_single_grain_ages (
  id integer(32,0) NOT NULL PRIMARY KEY,
  ft_datapoint_id integer(32,0) NOT NULL,
  grain_id character varying(100) NOT NULL,
  mount_id character varying(50),
  etch_duration_seconds integer(32,0),
  u_ppm numeric(10,3),
  u_ppm_error numeric(10,3),
  u_ca_ratio numeric(10,6),
  u_ca_ratio_error numeric(10,6),
  u_ca_error_type character varying(20),
  rmr0 numeric(6,4),
  kappa numeric(6,4),
  grain_age_ma numeric(10,2),
  grain_age_error_ma numeric(10,2),
  grain_age_error_type character varying(20),
  comments text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: ft_single_grain_ages.ft_datapoint_id -> ft_datapoints.id

CREATE TABLE ft_track_length_data (
  id integer(32,0) NOT NULL PRIMARY KEY,
  ft_datapoint_id integer(32,0) NOT NULL,
  grain_id character varying(100) NOT NULL,
  track_id character varying(100) NOT NULL,
  track_type character varying(20),
  mount_id character varying(50),
  etch_duration_seconds integer(32,0),
  apparent_length_um numeric(6,3),
  corrected_z_depth_um numeric(8,2),
  true_length_um numeric(6,3),
  azimuth_deg numeric(6,2),
  dip_deg numeric(6,2),
  angle_to_c_axis_deg numeric(6,2),
  c_axis_corrected_length_um numeric(6,3),
  dpar_um numeric(6,3),
  dpar_error_um numeric(6,3),
  n_dpar_measurements integer(32,0),
  dper_um numeric(6,3),
  dper_error_um numeric(6,3),
  n_dper_measurements integer(32,0),
  dpar_dper_error_type character varying(20),
  rmr0 numeric(6,4),
  kappa numeric(6,4),
  comments text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: ft_track_length_data.ft_datapoint_id -> ft_datapoints.id

CREATE TABLE grains (
  id integer(32,0) NOT NULL PRIMARY KEY,
  grain_id character varying(100) NOT NULL,
  mount_id character varying(50),
  grain_identifier character varying(100),
  grain_morphology character varying(50),
  grain_quality character varying(50),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: grains.mount_id -> mounts.mount_id

CREATE TABLE he_datapoints (
  id integer(32,0) NOT NULL PRIMARY KEY,
  sample_id character varying(50) NOT NULL,
  datapoint_key character varying(100) NOT NULL,
  batch_id integer(32,0),
  laboratory character varying(200),
  analyst_orcid character varying(50),
  analysis_date timestamp without time zone,
  publication_doi character varying(100),
  mineral_type character varying(50),
  mount_id character varying(50),
  n_aliquots integer(32,0),
  mean_uncorr_age_ma numeric(10,2),
  mean_uncorr_age_error_ma numeric(10,2),
  mean_uncorr_age_error_type character varying(20),
  weighted_mean_uncorr_age_ma numeric(10,2),
  weighted_mean_uncorr_age_error_ma numeric(10,2),
  weighted_mean_uncorr_age_error_type character varying(20),
  mswd_uncorr numeric(8,4),
  conf95_uncorr_ma numeric(10,2),
  chi2_uncorr_pct numeric(6,3),
  iqr_uncorr_ma numeric(10,2),
  mean_corr_age_ma numeric(10,2),
  mean_corr_age_error_ma numeric(10,2),
  mean_corr_age_error_type character varying(20),
  weighted_mean_corr_age_ma numeric(10,2),
  weighted_mean_corr_age_error_ma numeric(10,2),
  weighted_mean_corr_age_error_type character varying(20),
  mswd_corr numeric(8,4),
  conf95_corr_ma numeric(10,2),
  chi2_corr_pct numeric(6,3),
  iqr_corr_ma numeric(10,2),
  uncertainty_description text,
  ablation_pit_volume_method character varying(100),
  ablation_pit_volume_software character varying(100),
  he_measurement_method character varying(100),
  parent_isotope_method character varying(100),
  surface_area_volume_equation character varying(100),
  alpha_stopping_distance_ref character varying(200),
  ft_correction_equation character varying(100),
  esr_sa_v_equation character varying(100),
  esr_ft_equation character varying(100),
  eu_equation character varying(100),
  he_age_approach character varying(100),
  corr_age_method character varying(100),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: he_datapoints.batch_id -> batches.id

CREATE TABLE he_whole_grain_data (
  id integer(32,0) NOT NULL PRIMARY KEY,
  he_datapoint_id integer(32,0) NOT NULL,
  lab_no character varying(50),
  grain_identifier character varying(100),
  aliquot_type character varying(20),
  n_grains_in_aliquot integer(32,0),
  crystal_integrity character varying(20),
  grain_morphology character varying(50),
  assumed_geometry character varying(50),
  length_um numeric(10,2),
  length_um_sd numeric(10,2),
  half_width_um numeric(10,2),
  width_um_sd numeric(10,2),
  height_um numeric(10,2),
  height_um_sd numeric(10,2),
  measurement_method character varying(100),
  crystal_faces_measured character varying(200),
  he_ncc numeric(12,6),
  he_measurement_method character varying(100),
  he_extraction_temperature_c numeric(6,2),
  he_extraction_duration_min integer(32,0),
  he_extraction_method character varying(100),
  he_blank_ncc numeric(12,6),
  he_blank_error_ncc numeric(12,6),
  u_ppm numeric(10,3),
  u_ppm_error numeric(10,3),
  th_ppm numeric(10,3),
  th_ppm_error numeric(10,3),
  sm_ppm numeric(10,3),
  sm_ppm_error numeric(10,3),
  eu_ppm numeric(10,3),
  u_measurement_method character varying(100),
  u_blank_ppm numeric(10,6),
  th_blank_ppm numeric(10,6),
  sm_blank_ppm numeric(10,6),
  spike_u238_u235_ratio numeric(10,6),
  spike_th232_th229_ratio numeric(10,6),
  mass_mg numeric(10,6),
  surface_area_mm2 numeric(10,6),
  volume_mm3 numeric(10,6),
  sa_v_ratio numeric(10,6),
  rs_um numeric(10,2),
  esr_sa_v_um numeric(10,2),
  esr_ft_um numeric(10,2),
  sa_v_calc_equation character varying(100),
  ft_correction_equation character varying(100),
  alpha_stopping_distance_ref character varying(200),
  uncorr_age_ma numeric(10,2),
  uncorr_age_error_ma numeric(10,2),
  corr_age_ma numeric(10,2),
  corr_age_error_ma numeric(10,2),
  corr_age_1sigma_ma numeric(10,2),
  ft numeric(6,4),
  error_type character varying(20),
  eu_equation character varying(100),
  he_age_approach character varying(100),
  lambda_u238 character varying(30),
  lambda_th232 character varying(30),
  lambda_sm147 character varying(30),
  terminations character varying(10),
  std_run character varying(10),
  thermal_model character varying(10),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: he_whole_grain_data.he_datapoint_id -> he_datapoints.id

CREATE TABLE mounts (
  id integer(32,0) NOT NULL PRIMARY KEY,
  mount_id character varying(50) NOT NULL,
  mount_name character varying(200),
  mount_date date,
  sample_id character varying(50),
  etchant_chemical character varying(100),
  etch_duration_seconds integer(32,0),
  etch_temperature_c numeric(5,2),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE people (
  id integer(32,0) NOT NULL PRIMARY KEY,
  orcid character varying(50),
  name character varying(200) NOT NULL,
  email character varying(200),
  affiliation character varying(300),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference_materials (
  id integer(32,0) NOT NULL PRIMARY KEY,
  batch_id integer(32,0) NOT NULL,
  material_name character varying(100) NOT NULL,
  material_type character varying(50),
  expected_age_ma numeric(10,2),
  expected_age_error_ma numeric(10,2),
  measured_age_ma numeric(10,2),
  measured_age_error_ma numeric(10,2),
  parameter_type character varying(50),
  measured_value numeric(15,6),
  expected_value numeric(15,6),
  error numeric(15,6),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: reference_materials.batch_id -> batches.id

CREATE TABLE sample_people_roles (
  id integer(32,0) NOT NULL PRIMARY KEY,
  sample_id character varying(50) NOT NULL,
  person_id integer(32,0) NOT NULL,
  role character varying(50) NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: sample_people_roles.person_id -> people.id

CREATE TABLE samples (
  sample_id character varying(50) NOT NULL PRIMARY KEY,
  dataset_id integer(32,0) DEFAULT 1,
  igsn character varying(20),
  latitude numeric(10,7),
  longitude numeric(10,7),
  elevation_m numeric(8,2),
  geodetic_datum character varying(20) DEFAULT 'WGS84'::character varying,
  vertical_datum character varying(50) DEFAULT 'mean sea level'::character varying,
  lat_long_precision_m integer(32,0),
  lithology character varying(100),
  mineral_type character varying(50),
  sample_kind character varying(100),
  sample_method character varying(100),
  sample_depth_m numeric(8,2),
  sampling_location_information text,
  stratigraphic_unit character varying(200),
  chronostratigraphic_unit_age character varying(100),
  sample_age_ma numeric(10,2),
  sample_collector character varying(200),
  collection_date date,
  analyst character varying(100),
  analysis_method character varying(100),
  last_known_sample_archive character varying(200),
  associated_references text,
  n_aft_grains integer(32,0),
  n_ahe_grains integer(32,0),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- FK: samples.dataset_id -> datasets.id

-- Total tables: 19
