-- Database Schema Snapshot
-- Generated: 2025-11-23 20:50:00
-- Database: Supabase PostgreSQL (Thermochronology Database)
-- Generated by: /bigtidy living documentation system
-- Tables: earthbank_samples, earthbank_ftDatapoints, earthbank_heDatapoints,
--         earthbank_ftTrackLengthData, earthbank_heWholeGrainData

-- ============================================================================
-- EARTHBANK SCHEMA (v2.1 - EarthBank-Inspired camelCase)
-- Migration completed: 2025-11-18 (IDEA-014)
-- Current state: 5 tables with 98 camelCase columns total
-- ============================================================================

CREATE TABLE earthbank_samples (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "sampleID" varchar(255) NOT NULL,
  "IGSN" varchar(20),
  "latitude" numeric(10,6),
  "longitude" numeric(10,6),
  "elevationM" numeric(10,2),
  "geodeticDatum" varchar(50),
  "verticalDatum" varchar(50),
  "mineral" varchar(100),
  "mineralType" varchar(100),
  "lithology" varchar(100),
  "sampleKind" varchar(100),
  "sampleAgeMa" numeric(10,2),
  "collector" varchar(255),
  "collectionDate" date,
  "collectionYear" integer,
  "datasetID" varchar(100),
  "nAFTGrains" integer,
  "nAHeGrains" integer,
  "quadrangle" varchar(255),
  "faultBlock" varchar(100),
  "igneousAgeMa" numeric(10,2),
  "igneousAgeErrorMa" numeric(10,2),
  "project" varchar(255),
  "country" varchar(100),
  "stateProvince" varchar(100),
  "locationDescription" text,
  "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE ("sampleID"),
  UNIQUE ("IGSN")
);

CREATE TABLE earthbank_ftDatapoints (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "datapointName" varchar(255) NOT NULL,
  "sampleID" varchar(255) NOT NULL,
  "laboratory" varchar(255),
  "analyst" varchar(255),
  "analysisDate" timestamp without time zone,
  "labNumber" varchar(100),
  "ftMethod" varchar(100),
  "mineralType" varchar(100),
  "nGrains" integer,
  "totalNs" integer,
  "rhoS" numeric(15,6),
  "uPpm" numeric(10,2),
  "uPpmStdDev" numeric(10,2),
  "uConcentration" numeric(10,2),
  "dPar" numeric(10,3),
  "dParUncertainty" numeric(10,3),
  "pChi2" numeric(10,2),
  "dispersion" numeric(10,4),
  "pooledAgeMa" numeric(10,2),
  "pooledAgeUncertainty" numeric(10,2),
  "centralAgeMa" numeric(10,2),
  "centralAgeUncertainty" numeric(10,2),
  "mtl" numeric(10,3),
  "mtlUncertainty" numeric(10,3),
  "stdDevMu" numeric(10,3),
  "nTracks" integer,
  "sigmaP" numeric(10,4),
  "sigmaPError" numeric(10,4),
  "zeta" numeric(12,4),
  "zetaUncertainty" numeric(12,4),
  "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE ("datapointName"),
  FOREIGN KEY ("sampleID") REFERENCES earthbank_samples("sampleID") ON DELETE CASCADE
);

CREATE TABLE earthbank_ftTrackLengthData (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "datapointName" varchar(255) NOT NULL,
  "sampleID" varchar(255),
  "grainName" varchar(100),
  "trackID" varchar(100),
  "trackType" varchar(100),
  "lengthUm" numeric(10,3),
  "cAxisAngleDeg" numeric(10,2),
  "dPar" numeric(10,3),
  "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("datapointName") REFERENCES earthbank_ftDatapoints("datapointName") ON DELETE CASCADE
);

CREATE TABLE earthbank_heDatapoints (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "datapointName" varchar(255) NOT NULL,
  "sampleID" varchar(255) NOT NULL,
  "ftMethod" varchar(100),
  "laboratory" varchar(255),
  "analyst" varchar(255),
  "analysisDate" timestamp without time zone,
  "nGrains" integer,
  "meanCorrectedAgeMa" numeric(10,2),
  "meanCorrectedAgeUncertainty" numeric(10,2),
  "meanUncorrectedAgeMa" numeric(10,2),
  "notes" text,
  "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE ("datapointName"),
  FOREIGN KEY ("sampleID") REFERENCES earthbank_samples("sampleID") ON DELETE CASCADE
);

CREATE TABLE earthbank_heWholeGrainData (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "datapointName" varchar(255) NOT NULL,
  "sampleID" varchar(255),
  "grainName" varchar(100) NOT NULL,
  "correctedHeAge" numeric(10,2),
  "correctedHeAgeUncertainty" numeric(10,2),
  "uncorrectedHeAge" numeric(10,2),
  "uncorrectedHeAgeUncertainty" numeric(10,2),
  "ft" numeric(10,4),
  "ftU238" numeric(10,4),
  "ftU235" numeric(10,4),
  "ftTh232" numeric(10,4),
  "ftSm147" numeric(10,4),
  "he4Concentration" numeric(15,6),
  "he4ConcentrationUncertainty" numeric(15,6),
  "heNmolG" numeric(15,6),
  "heNmolGUncertainty" numeric(15,6),
  "uConcentration" numeric(10,2),
  "uConcentrationUncertainty" numeric(10,2),
  "uNg" numeric(15,6),
  "uNgUncertainty" numeric(15,6),
  "thConcentration" numeric(10,2),
  "thConcentrationUncertainty" numeric(10,2),
  "thNg" numeric(15,6),
  "thNgUncertainty" numeric(15,6),
  "smConcentration" numeric(10,2),
  "smConcentrationUncertainty" numeric(10,2),
  "smNg" numeric(15,6),
  "smNgUncertainty" numeric(15,6),
  "eU" numeric(10,2),
  "eUUncertainty" numeric(10,2),
  "massMg" numeric(15,8),
  "massMgUncertainty" numeric(15,8),
  "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("datapointName") REFERENCES earthbank_heDatapoints("datapointName") ON DELETE CASCADE
);

-- End of schema snapshot
