-- Generated: 2025-11-18 18:13:51
-- Database: neondb
-- Generated by: /bigtidy living documentation system


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 


> thermo-app@1.0.0 db:psql
> ./scripts/db/psql-direct.sh -c SELECT 'CREATE TABLE public.' || quote_ident('') || ' (' || string_agg(quote_ident(column_name) || ' ' || column_type, ', ') || ');' FROM (SELECT column_name, CASE WHEN data_type = 'ARRAY' THEN udt_name || '[]' WHEN data_type = 'USER-DEFINED' THEN udt_name ELSE udt_name END || CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END AS column_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '' ORDER BY ordinal_position) cols; -t

🔗 Connecting to: postgresql://neondb_owner:***@ep-fragrant-bush-ahfxu1xq.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
 

