import { getPool } from '../lib/db/connection';

async function generateSchemaSnapshot() {
  const pool = getPool();

  try {
    // Get all tables
    const tablesResult = await pool.query(`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);

    console.log('-- Database Schema Snapshot');
    console.log('-- Generated:', new Date().toISOString().split('T')[0], new Date().toISOString().split('T')[1].split('.')[0]);
    console.log('-- Database: AusGeochem Thermochronology (Neon PostgreSQL)');
    console.log('-- Generated by: /bigtidy living documentation system');
    console.log('');

    const tables = [];

    for (const row of tablesResult.rows) {
      const tableName = row.table_name;

      // Get table structure
      const columnsResult = await pool.query(`
        SELECT
          column_name,
          data_type,
          character_maximum_length,
          numeric_precision,
          numeric_scale,
          is_nullable,
          column_default
        FROM information_schema.columns
        WHERE table_name = $1
        AND table_schema = 'public'
        ORDER BY ordinal_position
      `, [tableName]);

      // Get primary keys
      const pkResult = await pool.query(`
        SELECT a.attname
        FROM pg_index i
        JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
        WHERE i.indrelid = $1::regclass
        AND i.indisprimary
      `, [tableName]);

      const primaryKeys = pkResult.rows.map(r => r.attname);

      // Get foreign keys
      const fkResult = await pool.query(`
        SELECT
          tc.constraint_name,
          kcu.column_name,
          ccu.table_name AS foreign_table_name,
          ccu.column_name AS foreign_column_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage AS ccu
          ON ccu.constraint_name = tc.constraint_name
          AND ccu.table_schema = tc.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
        AND tc.table_name = $1
      `, [tableName]);

      console.log(`CREATE TABLE ${tableName} (`);

      const columns = columnsResult.rows.map(col => {
        let def = `  ${col.column_name} ${col.data_type}`;

        if (col.character_maximum_length) {
          def += `(${col.character_maximum_length})`;
        } else if (col.numeric_precision && col.numeric_scale !== null) {
          def += `(${col.numeric_precision},${col.numeric_scale})`;
        }

        if (col.is_nullable === 'NO') {
          def += ' NOT NULL';
        }

        if (col.column_default && !col.column_default.includes('nextval')) {
          def += ` DEFAULT ${col.column_default}`;
        }

        if (primaryKeys.includes(col.column_name)) {
          def += ' PRIMARY KEY';
        }

        return def;
      });

      console.log(columns.join(',\n'));
      console.log(');');
      console.log('');

      // Output foreign keys separately
      if (fkResult.rows.length > 0) {
        for (const fk of fkResult.rows) {
          console.log(`-- FK: ${tableName}.${fk.column_name} -> ${fk.foreign_table_name}.${fk.foreign_column_name}`);
        }
        console.log('');
      }

      tables.push({
        name: tableName,
        columns: columnsResult.rows.length,
        primaryKeys,
        foreignKeys: fkResult.rows
      });
    }

    console.log('-- Total tables:', tables.length);

  } catch (error) {
    console.error('Error generating schema:', error);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

generateSchemaSnapshot();
