#!/bin/bash
# Demonstration script for caption extraction functionality

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Caption Extraction Script Demo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script demonstrates the updated caption extraction workflow:"
echo ""
echo "✅ FEATURES:"
echo "  1. Extract figure captions from plain-text.txt"
echo "  2. Match captions to images (filter by size)"
echo "  3. RENAME image files to use figure names"
echo "     Example: page_4_img_0.jpeg → figure_1.jpeg"
echo "  4. Extract table captions from plain-text.txt"
echo "  5. Create table-metadata.json with full captions"
echo ""
echo "📦 OUTPUT FILES:"
echo "  - images/image-metadata.json (updated with renamed files + captions)"
echo "  - images/image-metadata.backup.json (backup of original)"
echo "  - images/table-metadata.json (NEW: table captions)"
echo "  - images/figure_*.{jpeg|png} (renamed image files)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 USAGE:"
echo ""
echo "  npx tsx scripts/extract-figure-captions.ts \\"
echo "    text/plain-text.txt \\"
echo "    images/image-metadata.json"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 INTEGRATION IN /thermoanalysis:"
echo ""
echo "  This is now STEP 7.7 in the /thermoanalysis workflow."
echo "  After extracting images from PDF (STEP 7), run this script"
echo "  to filter, rename, and extract table metadata."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show script location
SCRIPT_PATH="scripts/extract-figure-captions.ts"
if [ -f "$SCRIPT_PATH" ]; then
    echo "✅ Script found: $SCRIPT_PATH"
    echo ""
    echo "Lines of code: $(wc -l < "$SCRIPT_PATH")"
    echo ""
else
    echo "❌ Script not found: $SCRIPT_PATH"
    exit 1
fi

echo "🎯 KEY IMPROVEMENTS:"
echo ""
echo "  BEFORE:"
echo "    - Images: page_4_img_0.jpeg, page_7_img_1.jpeg (hard to identify)"
echo "    - No table captions (only screenshot files)"
echo "    - Logos and small graphics mixed with figures"
echo ""
echo "  AFTER:"
echo "    - Images: figure_1.jpeg, figure_2.jpeg (clear identification)"
echo "    - Table captions in searchable JSON"
echo "    - Only scientifically relevant figures kept"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Ready to use! Run the command above in your paper directory."
echo ""
